---
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-disabled-endpoints
  namespace: rhoso2
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Run after OpenStackControlPlane (wave 0)
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: cleanup-disabled-endpoints
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      containers:
      - name: cleanup
        image: quay.io/podified-antelope-centos9/openstack-openstackclient:current-podified
        command:
        - /bin/bash
        - -c
        - |
          set -e

          # Extract SSL certificate
          echo "Extracting SSL certificate..."
          mkdir -p /tmp/certs
          cat /var/run/secrets/ssl/ca.crt > /tmp/certs/ca.crt
          export OS_CACERT=/tmp/certs/ca.crt

          # Get credentials from the secret
          export OS_AUTH_URL=https://keystone-internal-rhoso2.apps-crc.testing
          export OS_USERNAME=admin
          export OS_PASSWORD=$(cat /var/run/secrets/openstack/AdminPassword)
          export OS_PROJECT_NAME=admin
          export OS_USER_DOMAIN_NAME=Default
          export OS_PROJECT_DOMAIN_NAME=Default
          export OS_IDENTITY_API_VERSION=3

          # Wait for Keystone to be ready
          echo "Waiting for Keystone to be ready..."
          RETRY_COUNT=0
          MAX_RETRIES=30
          RETRY_DELAY=10

          until curl --cacert ${OS_CACERT} -s -o /dev/null -w "%{http_code}" ${OS_AUTH_URL} | grep -q "^[23]"; do
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "Keystone did not become ready after ${MAX_RETRIES} attempts"
              exit 1
            fi
            echo "Waiting for Keystone to respond... (attempt $RETRY_COUNT/$MAX_RETRIES)"
            sleep $RETRY_DELAY
          done

          echo "Keystone is responding, testing authentication..."
          openstack token issue || { echo "Authentication failed!"; exit 1; }

          echo "Cleaning up orphaned Cinder endpoints..."
          # Delete all Cinder endpoints
          CINDER_ENDPOINTS=$(openstack endpoint list --service cinderv3 -f value -c ID 2>/dev/null || true)
          if [ -n "$CINDER_ENDPOINTS" ]; then
            for ep in $CINDER_ENDPOINTS; do
              echo "Deleting Cinder endpoint: $ep"
              openstack endpoint delete $ep || true
            done
          else
            echo "No Cinder endpoints found"
          fi

          # Delete Cinder service
          if openstack service show cinderv3 >/dev/null 2>&1; then
            echo "Deleting Cinder service..."
            openstack service delete cinderv3 || true
          else
            echo "Cinder service not found"
          fi

          echo "Cleaning up orphaned Barbican endpoints..."
          # Delete all Barbican endpoints
          BARBICAN_ENDPOINTS=$(openstack endpoint list --service barbican -f value -c ID 2>/dev/null || true)
          if [ -n "$BARBICAN_ENDPOINTS" ]; then
            for ep in $BARBICAN_ENDPOINTS; do
              echo "Deleting Barbican endpoint: $ep"
              openstack endpoint delete $ep || true
            done
          else
            echo "No Barbican endpoints found"
          fi

          # Delete Barbican service
          if openstack service show barbican >/dev/null 2>&1; then
            echo "Deleting Barbican service..."
            openstack service delete barbican || true
          else
            echo "Barbican service not found"
          fi

          echo "Cleanup complete!"
          echo "Remaining public endpoints:"
          openstack endpoint list --interface public || echo "Could not list endpoints"
        volumeMounts:
        - name: osp-secret
          mountPath: /var/run/secrets/openstack
          readOnly: true
        - name: ssl-cert
          mountPath: /var/run/secrets/ssl
          readOnly: true
      volumes:
      - name: osp-secret
        secret:
          secretName: osp-secret
      - name: ssl-cert
        secret:
          secretName: rootca-public
