---
# Grant ArgoCD instance permissions to manage rhoso1 namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-rhoso1-manager
rules:
  # Permissions for managing OpenStack resources
  - apiGroups:
      - "core.openstack.org"
      - "network.openstack.org"
      - "dataplane.openstack.org"
      - "telemetry.openstack.org"
      - "heat.openstack.org"
      - "ironic.openstack.org"
      - "manila.openstack.org"
      - "ovn.openstack.org"
      - "rabbitmq.openstack.org"
      - "neutron.openstack.org"
      - "nova.openstack.org"
      - "cinder.openstack.org"
      - "glance.openstack.org"
      - "keystone.openstack.org"
      - "placement.openstack.org"
      - "mariadb.openstack.org"
      - "octavia.openstack.org"
      - "barbican.openstack.org"
      - "horizon.openstack.org"
    resources:
      - "*"
    verbs:
      - "*"
  # Permissions for Kubernetes core resources
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
      - configmaps
      - services
      - serviceaccounts
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/log
    verbs:
      - "*"
  # Permissions for storage
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - "*"
  # Permissions for batch jobs
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - "*"
  # Permissions for RBAC
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
  # Permissions for Apps
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - "*"
  # Permissions for Routes
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-rhoso1-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-rhoso1-manager
subjects:
  - kind: ServiceAccount
    name: gitops-rhoso1-argocd-application-controller
    namespace: gitops-rhoso1
---
# ClusterRole for ArgoCD application-controller to manage Applications cluster-wide
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-rhoso1-application-controller
rules:
  # Application controller needs cluster-wide access to Applications for sharding
  - apiGroups:
      - "argoproj.io"
    resources:
      - applications
      - applicationsets
      - appprojects
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-rhoso1-application-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-rhoso1-application-controller
subjects:
  - kind: ServiceAccount
    name: gitops-rhoso1-argocd-application-controller
    namespace: gitops-rhoso1
---
# ClusterRole for ArgoCD server to read Applications cluster-wide
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-rhoso1-server-reader
rules:
  # ArgoCD server needs to read Applications and ApplicationSets at cluster scope
  - apiGroups:
      - "argoproj.io"
    resources:
      - applications
      - applicationsets
      - appprojects
    verbs:
      - get
      - list
      - watch
  # Read access to namespaces to discover where apps can be deployed
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-rhoso1-server-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-rhoso1-server-reader
subjects:
  - kind: ServiceAccount
    name: gitops-rhoso1-argocd-server
    namespace: gitops-rhoso1
---
# Grant ArgoCD server access to view managed resources in rhoso1
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-rhoso1-server-admin
  namespace: rhoso1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: gitops-rhoso1-argocd-server
    namespace: gitops-rhoso1
