---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-rhoso1
  labels:
    argocd.argoproj.io/managed-by: gitops-rhoso1
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: gitops-rhoso1
  namespace: gitops-rhoso1
spec:
  # Server configuration
  server:
    replicas: 1
    route:
      enabled: true
      tls:
        termination: reencrypt
        insecureEdgeTerminationPolicy: Redirect
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    insecure: false
    # Disable admin user - use OpenShift OAuth instead
    # Set to false to allow admin user login alongside OAuth
    # extraArgs:
    #   - --disable-auth

  # Application controller
  controller:
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding:
      enabled: false

  # Repo server
  repo:
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi

  # Redis
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi

  # Enable OpenShift OAuth
  sso:
    provider: dex
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi

  # HA disabled for single-node/CRC
  ha:
    enabled: false

  # RBAC configuration - allow OpenShift users to login
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      # Grant admin role to cluster-admins group
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin

      # Grant admin role to specific OpenShift users (add your username here)
      # g, <your-openshift-username>, role:admin

      # Grant admin role to any authenticated OpenShift user
      g, system:authenticated, role:admin
    scopes: '[groups]'

  # Resource customizations for OpenStack CRDs
  resourceCustomizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
    core.openstack.org/OpenStackControlPlane:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = "OpenStackControlPlane is ready"
                return hs
              end
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for OpenStackControlPlane to be ready"
        return hs
    batch/v1/Job:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.succeeded ~= nil and obj.status.succeeded > 0 then
            hs.status = "Healthy"
            hs.message = "Job completed successfully"
            return hs
          end
          if obj.status.failed ~= nil and obj.status.failed > 0 then
            hs.status = "Degraded"
            hs.message = "Job failed"
            return hs
          end
        end
        hs.status = "Progressing"
        hs.message = "Job is running"
        return hs

  # Resource exclusions
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun

  # ApplicationSet controller
  applicationSet:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  # Notifications controller
  notifications:
    enabled: false

  # Status badge
  statusBadgeEnabled: true

  # Prometheus monitoring
  prometheus:
    enabled: true
    route:
      enabled: false

  # Source namespaces - where ArgoCD can deploy Applications from
  sourceNamespaces:
    - gitops-rhoso1

  # Configure to manage rhoso1 namespace
  # This will be set via RBAC after creation
