---
# ClusterRole and ClusterRoleBinding for PV generator job
# This must be applied separately as ArgoCD in namespaced mode cannot manage cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-generator
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "nodes"]
  verbs: ["get", "list", "create", "patch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-generator
subjects:
- kind: ServiceAccount
  name: pv-generator
  namespace: rhoso1
---
# ClusterRole and ClusterRoleBinding for storage prep job
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-prep
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-prep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-prep
subjects:
- kind: ServiceAccount
  name: storage-prep
  namespace: rhoso1
